### ISSUE TITLE
Question on DBContext and it's location in the project structure.

### ISSUE THREAD

**Issue by cland** [exceptionnotfound/RespositoryServicePatternDemo#1]
Thank you for this very useful and clear design pattern. Learnt a lot. 
I've been trying to structure my applications solution the way you have done it especially having to separate into 2 projects. 

I have a rest API I am building using .net core 3.1 and I have my context db defined connecting to mysql and all setup in my Startup.cs nicely. I was thinking of applying your repo-service architecture and i am just lost as to where the dbcontext will be defined, the class (In Repository-Service project?) and how it will then be setup/configured in the project where the Startup.cs, appsettings.json and controllers etc?

![reposervice-pattern](https://user-images.githubusercontent.com/4290381/78776439-27ec2a00-7998-11ea-96f2-44c83dd4915c.png)

Or given that I am writing a REST API is it even necessary to put the Repository-Service in one project and the main rest API implementation with controllers in another project?

**Comment by exceptionnotfound** [comment]
When I have used this pattern with Entity Framework contexts, I have generally had the EF context injected at the Repository layer. To do this, you have to add it to the Services collection in Startup.cs. I believe I've used the lifetime Transient for it.

For your other question, Repository/Service is merely a pattern, and whether it it is its own project or not should make no difference.
