### ISSUE TITLE
Question on nesting services

### ISSUE THREAD

**Issue by tbalasavage** [exceptionnotfound/RespositoryServicePatternDemo#2]
First, thanks for the post; that was helpful to see the pattern illustrated. 

My question is concerning services injected into services instead of repositories into services. In your example, the `FinancialsService` class has two properties: `ITicketRepository` and `IFoodRepository`. I'm envisioning a situation where the services that query the repositories have additional logic, such as filtering on the data retrieved from the repository, and aren't just pass through classes. In this case, I may want the filtered data and would prefer not to re-implement the filtering in multiple services.  My thought would be to inject the services instead of the repositories into `FinancialsService`. Would this situation violate the pattern that you describe?

**Comment by exceptionnotfound** [comment]
The Repositories and the Services comprise a "layer" of this architecture each, and generally you do not want to inject items in the same layer into one another; this often causes errors with your DI system. In your case, you might need a third layer (in ASP.NET this is often the Controllers) that have multiple Services injected to them, where you can do your logic combining. Just be aware that the more layers you have, the more complex the architecture is and the more difficult it is to test.

**Comment by tbalasavage** [comment]
@exceptionnotfound Thank you for the response and info. It was helpful.
